### ISSUE TITLE
Add lcoe filter in cluster selection

### ISSUE THREAD

**Issue by gschivley** [gschivley/pg_misc#1]
In addition to the `min_capacity` parameter, add a `max_lcoe` parameter that will filter base clusters. One or both parameters need to be specified.

**Comment by gschivley** [comment]
@ezwelty I'll take a crack at adding this to `master`.

**Comment by ezwelty** [comment]
@gschivley Shouldn't this be added to `renewables_clusters.py` on the `wind-solar-clusters` branch of PowerGenome? I really don't think we need to be maintaining two modules that do exactly the same thing.

**Comment by ezwelty** [comment]
Implemented on https://github.com/ezwelty/PowerGenome/tree/wind-solar-clusters.
